version: '3.7'
services:
  redis:
    image: redis:5.0
    # restart: always
    ports:
      - '6379:6379'
    networks:
      - backend
  mongo:
    image: mongo:4.2.1-bionic
    # restart: always
    ports:
      - '27017:27017'
    command: mongod
    networks:
      - backend
  postgres:
    image: postgres:12.1
    # restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  keycloak_postgres:
      image: postgres:12.1
      volumes:
        - keycloak_postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: jboss/keycloak:8.0.0
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: keycloak_postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - keycloak_postgres
  web:
    build: ./web
    ports:
      - "3001:3000"
    volumes:
      - ./web:/app
      - app/node_modules
    networks:
      - backend
  # links:
    # - redis
  # redis:
  #   image: redis
volumes:
  keycloak_postgres_data:
      driver: local
networks:
  backend:
    driver: bridge
